//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL404
    {
        public int ID { get; set; }
        public string VIDEO { get; set; }
        public string TEXT { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
