//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLANIMECOMMENTLIKE
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> ANIMECOMMENTID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLANIMECOMMENT TBLANIMECOMMENT { get; set; }
        public virtual TBLUSER TBLUSER { get; set; }
    }
}
