//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLANIME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLANIME()
        {
            this.TBLANIMECOMMENT = new HashSet<TBLANIMECOMMENT>();
            this.TBLEPISODE = new HashSet<TBLEPISODE>();
            this.TBLFAVORITES = new HashSet<TBLFAVORITES>();
            this.TBLNOTIFICATIONS = new HashSet<TBLNOTIFICATIONS>();
            this.TBLSEASON = new HashSet<TBLSEASON>();
            this.TBLWATCHLATER = new HashSet<TBLWATCHLATER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public string ANIMENAME { get; set; }
        public string EDIT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DETAIL { get; set; }
        public string TYPE { get; set; }
        public string BANNER { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<decimal> IMDB { get; set; }
        public Nullable<bool> ADMINSTATUS { get; set; }
        public string BIGBANNER { get; set; }
        public Nullable<decimal> MYANIMELIST { get; set; }
    
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLANIMECOMMENT> TBLANIMECOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPISODE> TBLEPISODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFAVORITES> TBLFAVORITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNOTIFICATIONS> TBLNOTIFICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSEASON> TBLSEASON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLWATCHLATER> TBLWATCHLATER { get; set; }
    }
}
