//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEPISODECOMMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEPISODECOMMENT()
        {
            this.TBLEPISODECOMMENTLIKE = new HashSet<TBLEPISODECOMMENTLIKE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> EPISODEID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> USTID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLEPISODE TBLEPISODE { get; set; }
        public virtual TBLUSER TBLUSER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPISODECOMMENTLIKE> TBLEPISODECOMMENTLIKE { get; set; }
    }
}
