//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEPISODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEPISODE()
        {
            this.TBLEPISODECOMMENT = new HashSet<TBLEPISODECOMMENT>();
            this.TBLEPISODELIKE = new HashSet<TBLEPISODELIKE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ANIMEID { get; set; }
        public Nullable<int> SEASONID { get; set; }
        public string EP1 { get; set; }
        public string EP2 { get; set; }
        public string EP3 { get; set; }
        public string EP4 { get; set; }
        public string EPINUMBER { get; set; }
        public string EPISODENAME { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TIME { get; set; }
        public string BANNER { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBLANIME TBLANIME { get; set; }
        public virtual TBLSEASON TBLSEASON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPISODECOMMENT> TBLEPISODECOMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPISODELIKE> TBLEPISODELIKE { get; set; }
    }
}
