//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFOLLOWERS
    {
        public int ID { get; set; }
        public Nullable<int> FOLLOWERID { get; set; }
        public Nullable<int> FOLLOWEDID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual TBLUSER TBLUSER { get; set; }
        public virtual TBLUSER TBLUSER1 { get; set; }
    }
}
