//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnitsukiTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUSER()
        {
            this.TBLEPISODELIKE = new HashSet<TBLEPISODELIKE>();
        }
    
        public int ID { get; set; }
        public string USERNAME { get; set; }
        public string MAIL { get; set; }
        public string PASSWORD { get; set; }
        public string PICTURE { get; set; }
        public string ABOUT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLEPISODELIKE> TBLEPISODELIKE { get; set; }
    }
}
